config/routes.rb
Huxap::Application.routes.draw do
  resources :interests
  

  resources :home do
    collection do
      get 'about'
      get 'contact'
      get 'home'
      get 'join'
    end
  end
  

  root :to => 'home#home'
  

end

app/models/interest.rb
class Interest  
  include Mongoid::Document  
  field :text, type: String
  
  
  def self.empty_text
    "Leave phone or email and we contact you"
    #"phone or email"
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html
  
  def about
  end
  def contact
  end
  def home
  end
  def join
  end
  
end

app/controllers/interests_controller.rb
class InterestsController < ApplicationController
  respond_to :html
  
  def new
    @interest = Interest.new
    respond_with(@interest)
  end
  
  def create
    @interest = Interest.new(params[:interest])
    respond_to do |format|
      @notice = "";
      if is_valid?(@interest) and @interest.save
        InterestMailer.notify_huxap(@interest)
        @notice = "Thanks, we contact you shortly!"
        #format.html { redirect_to(@interest, :notice => 'Thanks, we contact you shortly!') }
        #redirect_to :back        
      end
      format.html { redirect_to :back, :notice => @notice }
    end
  end
  
  def is_valid? interest
    interest.text != Interest.empty_text
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_foot.html.haml
We believe most innovative ideas are realized by diverse teams working together, give us a call +47 466 35 826 or email
%a{:href=>"mailto:kristine@huxap.com"} kristine@huxap.com 

app/views/home/about.html.haml
%div{:class => "span-21 prepend-3"}
  %h3 We build human oriented systems 
  %li define and focus on the top goals
  %li make sure everyone knows the specific job to be done to achieve the goals
  %li develop with lean and agile methodologies
  %li set up a regular cycle of follow-through  
  %li deliver well-tested product release every 1-3 months

  %hr{:class => "space"}

  %h3 Our senior developers 
  %li have worked in financial, marketing, media, social, mobile businesses
  %li obsessed with clean code and pragmatic programmer practices without any hope to recovery
  %li experienced with leading Microsoft.NET, Java and Ruby technologies building web, desktop and mobile solutions

  %hr{:class => "space"}

app/views/home/contact.html.haml
%div{:class => "span-6 prepend-1"}
  %hr{:class => "space"}
  %div We are located in Oslo and Riga 
  %li 1h timezone difference 
  %li 1h flight time distance
  
  
  %hr{:class => "space"}
 
  %b Oslo 
  
  %div
    Ullern alle 55, 0381 Oslo, Norway
    %br +47 466 35 826, 
    %a{:href=>"mailto:kristine@huxap.com"} kristine@huxap.com

  %hr{:class => "space"}
  %hr
  
  %b Riga 
  %div
    Lubanas iela 16, LV-1019, Riga, Latvia
    %br +47 466 35 826 
    %a{:href=>"mailto:kristine@huxap.com"} kristine@huxap.com

%div{:class => "span-17 last"}
  %img{:src=> "http://maps.google.com/maps/api/staticmap?center=58.6035,2217.711237&zoom=5&size=600x300&sensor=false&path=color:0x0000ff|weight:5|Riga,Latvia|Oslo,Norway"}

app/views/home/home.html.haml
%div{:class => "span-21 prepend-3"}
  
  %h3 Did you know...
  
  .quiet Covey quoted a Bain survey of senior executives:
  %li 96% of senior executives in 362 companies said their company was costumer-focused
  %li 80% believed their company delivered a superior cusotmer experience
  %li 8% of their customers agreed

  %hr{:class=>"space"}
  
  %h4 We know history, use facts and leave emotions. Huxap stands for holistic user experience through agile practices
  /.prepend-3=image_tag "growing_plant_rounded.jpg"
  .prepend-3 
    %img{:src=>"/assets/growing_plant_rounded.jpg", :alt=>""}
  
  %hr{:class=>"space"}
  
  %h3 We build software products and aim to improve organizational, technical and personal success

app/views/home/join.html.haml
%div{:class => "span-11 prepend-3"}
  %h3 We offer...
  %li build products with leading edge technologies
  %li continually learn, mentor and develop your career
  %li travel to work closely  at client sites in Oslo and Riga
  %li you choose the right technologies and tools for the job
  %li attend each year a world-class conference (e.g. NDC, NordicRuby)

%div{:class => "span-10 last"}
  %h3 We expect you...
  %li are passionate about programming
  %li use design patterns, refactoring and unit testing
  %li build software with SOLID principles in mind
  %li are familiar with lean and agile methodologies
  %li be part of diverse, highly skilled teams and join our kaizen culture

%hr{:class => "space"}

%div{:class => "span-11 prepend-3"}
  %h3 Currently looking for...
  %li Senior .Net developers 
  %li Senior Ruby developers 
  %li Senior Java developers 
  %li Junior level developers or students willing to learn

%div{:class => "span-10 last"}
  %h3 Technologies we use...
  %li languages: c#, ruby, java
  %li frameworks: Microsoft.NET stack, Ruby on Rails
  %li uni testing with: NUnit, Moq, RSpec, Cucumber
  %li relational databases: MS SQL, Oracle, MySQL 
  %li non-relational databases: MongoDB, Redis
  %li continuous integration: Team City, TFS Build 
  %li source control: TFS, Git
  %li if your technology is not mentioned we would love to hear your success story

%hr{:class => "space"}

%div{:class => "span-7"}
  %br
%div{:class => "span-10 large"}
  .info 
    Send your resume to 
    %a{:href=>"mailto:edijs.petersons@huxap.com?subject=Job"} edijs.petersons@huxap.com 
%div{:class => "span-7 last"}

app/views/interests/_new.html.haml
= form_for(@interest = Interest.new) do |f|
  - unless notice.blank?
    .silent
      .weContactYouConfirmation= notice
  - else
    %input{:id => "interest_empty_text", :type => "hidden", :value => Interest.empty_text}
    %input{:id=>"interest_text", :name=>"interest[text]", :type=>"text", :class=>"interestText", :size=>"50" }
    %button{:type=>"submit", :class=>"button positive"} 
      %img{:src=>"/assets/tick.png", :alt=>""} Contact me

app/views/interests/new.html.haml
%div{ :id => "notice"}= notice
= form_for(@interest) do |f| 
  %div{:class => "field"}
    = f.text_field :text, :size => 40
    = f.submit "Contact me"

app/views/layouts/application.html.haml
!!! XML
!!!
%head
  %title Huxap
  = stylesheet_link_tag :application
  = javascript_include_tag :application
  = csrf_meta_tag
  <!--[if lt IE 8]><link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->

%body
  .container
    / HEAD
    %div{:class => "span-4 colborder"}
      .huxap
        =link_to "Huxap", "/"
      .quiet
        %i Building software products
    %div{:class => "span-12 menu"}
      %li=link_to "Home", "/" #new_interest_path
      %li=link_to "About us", "/home/about"
      %li=link_to "Contact us", "/home/contact"
      %li=link_to "Join us", "/home/join" 
    %div{:class => "span-6 last"}
    
    %hr
    
    / MAIN
    = yield
    / FOOT 
    %hr
    %div{:class => "span-24 centerText"}
      = render :partial => "foot"
    %div{:class => "span-24 centerText"}
      = render :partial => "/interests/new"	